on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  clang-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Google Test
        run: |
          sudo apt install -y libgtest-dev
          cd /usr/src/googletest
          sudo cmake .
          sudo make
          sudo cp lib/libgtest.a /usr/lib
          sudo cp lib/libgmock.a /usr/lib

      - name: Install clang-tidy and clang-format
        run: |
          sudo apt update
          sudo apt install -y clang-tidy clang-format

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake ..
          make

          ./VectorTest

      - name: Check formatting with clang-format
        run: |
          clang-format --dry-run -Werror *.cpp

      - name: Check code with clang-tidy
        run: |
          clang-tidy *.cpp -- -std=c++20
